from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ...models import SessionState


@runtime_checkable
class SessionRepository(Protocol):
    def create(self, *, tenant_id: str = ..., student_user_id: str = ..., class_id: str = ..., student_id: str = ...) -> SessionState: ...
    def get(self, session_id: str, *, tenant_id: str | None = ..., student_user_id: str | None = ...) -> SessionState: ...
    def save(self, state: SessionState) -> None: ...
    def metadata(self, session_id: str) -> dict: ...
    def assign_owner(self, session_id: str, *, tenant_id: str, student_user_id: str, class_id: str = ...) -> SessionState: ...
    def list(self, limit: int = ..., *, tenant_id: str | None = ..., class_id: str | None = ..., student_user_id: str | None = ...) -> list[tuple[SessionState, str]]: ...
    def delete_session(self, session_id: str, *, tenant_id: str) -> bool: ...


@runtime_checkable
class IdentityRepository(Protocol):
    def get_tenant(self, tenant_id: str) -> dict: ...
    def list_tenants(self) -> list[dict]: ...
    def get_user(self, user_id: str, include_memberships: bool = ...) -> dict: ...
    def list_users(self, tenant_id: str, role: str | None = ...) -> list[dict]: ...
    def list_classes(self, tenant_id: str) -> list[dict]: ...
    def anonymize_user_identity(self, *, user_id: str, tenant_id: str) -> dict: ...


@runtime_checkable
class ArtifactRepository(Protocol):
    def list_session(self, session_id: str, *, tenant_id: str | None = ..., all_versions: bool = ...) -> list[dict]: ...
    def get(self, artifact_id: str, *, tenant_id: str | None = ...) -> dict: ...
    def delete_session(self, session_id: str, *, tenant_id: str) -> int: ...


@runtime_checkable
class EvidenceRepository(Protocol):
    def list_session(self, session_id: str, *, tenant_id: str | None = ...) -> list[dict]: ...
    def delete_session(self, session_id: str, *, tenant_id: str) -> int: ...


@runtime_checkable
class WorkflowRepository(Protocol):
    def snapshot(self, session_id: str, **kwargs: Any) -> dict: ...
    def delete_session(self, session_id: str, *, tenant_id: str) -> dict: ...


@runtime_checkable
class FeedbackRepository(Protocol):
    def list_feedback(self, session_id: str, status: str | None = ..., *, tenant_id: str | None = ...) -> list[dict]: ...
    def delete_session(self, session_id: str, *, tenant_id: str) -> dict: ...


@runtime_checkable
class TaskRepository(Protocol):
    def list_tasks(self, *, tenant_id: str | None = ..., session_id: str | None = ..., status: str | None = ..., limit: int = ...) -> list[dict]: ...


@runtime_checkable
class KnowledgeRepository(Protocol):
    def stats(self, *, tenant_id: str | None = ...) -> dict: ...


@runtime_checkable
class JobRepository(Protocol):
    def stats(self, *, tenant_id: str | None = ...) -> dict: ...


@runtime_checkable
class AnalyticsRepository(Protocol):
    def analytics_summary(self, tenant_id: str) -> dict[str, Any]: ...


@runtime_checkable
class CommercialRepository(Protocol):
    def subscription(self, tenant_id: str) -> dict[str, Any]: ...
    def entitlement(self, tenant_id: str, feature: str, default: Any = ...) -> Any: ...
    def check_ai_quota(self, tenant_id: str) -> tuple[bool, str]: ...


@runtime_checkable
class ModelUsageRepository(Protocol):
    def usage_summary(self, days: int = ..., tenant_id: str | None = ...) -> dict: ...


@runtime_checkable
class ProjectRepositoryProtocol(Protocol):
    def ensure_default_template(self, *, tenant_id: str, created_by: str = ...) -> dict[str, Any]: ...
    def list_templates(self, *, tenant_id: str, published_only: bool = ...) -> list[dict[str, Any]]: ...
    def get_template(self, template_id: str, *, tenant_id: str) -> dict[str, Any]: ...
    def get_template_version(self, template_version_id: str, *, tenant_id: str) -> dict[str, Any]: ...
    def create_project(self, *, tenant_id: str, owner_user_id: str, template_version_id: str, session_id: str, name: str = ...) -> dict[str, Any]: ...
    def list_projects(self, *, tenant_id: str, owner_user_id: str, status: str | None = ...) -> list[dict[str, Any]]: ...
    def get_project(self, project_id: str, *, tenant_id: str, owner_user_id: str) -> dict[str, Any]: ...
    def save_answer(self, project_id: str, question_id: str, answer: Any, *, tenant_id: str, owner_user_id: str) -> dict[str, Any]: ...
    def list_answers(self, project_id: str, *, tenant_id: str, owner_user_id: str) -> dict[str, Any]: ...
